imports:
    - { resource: parameters.yml }
#    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [ JoostNijhuisPackageManagerBundle ]
    java:           "/usr/bin/java"
    #java:          "C:\Program Files\Java\jre7\bin\java.exe"
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

joost_nijhuis_package_manager:
    app_name:                     %app_name%
    company_name:                 %company_name%
    company_url:                  %company_url%
    enable_packagist_proxy:       %enable_packagist_proxy%
    parse_packages:               %parse_packages%
    attach_private_packages:      %attach_private_packages%
    packagist_url:                %packagist_url%
    download_url_prefix:          %download_url_prefix%
    private_packages_config_file: %private_packages_config_file%
    private_packages_output_file: %private_packages_output_file%
    private_packages_data_dir:    %private_packages_data_dir%
    packages_index_dir:           %packages_index_dir%
    tmp_dir:                      %tmp_dir%
