parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     
    database_user:     
    database_password: 

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    app_name:                     "{RepositoryName}"
    company_name:                 "{CompanyName}"
    company_url:                  "http://www.example.com"
    enable_packagist_proxy:       true
    parse_packages:               true
    attach_private_packages:      true
    packagist_url:                "http://packagist.org"
    download_url_prefix:          "http://www.example.com/downloads/"
    private_packages_config_file: %kernel.root_dir%/config/repository_config.json
    private_packages_output_file: %kernel.root_dir%/../data/private_packages.json
    private_packages_data_dir:    %kernel.root_dir%/../data/packages
    packages_index_dir:           %kernel.root_dir%/../data/index
    tmp_dir:                      %kernel.root_dir%/tmp
