<?php

/**
 * This file is part of the Composer Package Manager.
 *
 * (c) Joost Nijhuis <jnijhuis81@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace JoostNijhuis\PackageManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LanguagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguagesRepository extends EntityRepository
{
    
    /**
     * @return array:
     */
    public function getForSelectBox()
    {
        $retVal = array();
        $data = $this->createQueryBuilder('l')
            ->select('l.code, l.name')
            ->where('l.active = 1')
            ->orderBy('l.sortorder', 'ASC')
            ->getQuery()
            ->getArrayResult();
        
        foreach ($data as $index => $record) {
            $retVal[$record['code']] = $record['name'];
        }
        
        return $retVal;
    }
    
    public function getAvailableLocales()
    {
        $retVal = array();
        $data = $this->createQueryBuilder('l')
            ->select('l.code')
            ->where('l.active = 1')
            ->orderBy('l.sortorder', 'ASC')
            ->getQuery()
            ->getArrayResult();
        
        foreach ($data as $index => $record) {
            $retVal[] = $record['code'];
        }
        
        return $retVal;
    }

}
