<?php

/**
 * This file is part of the Composer Package Manager.
 *
 * (c) Joost Nijhuis <jnijhuis81@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace JoostNijhuis\PackageManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JoostNijhuis\PackageManagerBundle\Entity\SvnAuthenticationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SvnAuthenticationsRepository extends EntityRepository
{

}
